---
# General
docker_dir: "/home/{{ ansible_user }}/docker"
backup_dir: "/home/{{ ansible_user }}/backups"
backup_retention_days: 14
timezone: America/Toronto

# Vaultwarden
vaultwarden_signups_allowed: "false"
vaultwarden_websocket_enabled: "true"

# AdGuard
adguard_dns_port: 53
adguard_web_port: 3000

# Paperless
paperless_db_name: "Paperless"
paperless_user_name: "Paperless"

# NextCloud
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"

# OpenCloud
opencloud_admin_password: "admin"
