---
# # General
# backup_retention_days: 14
# timezone: America/Toronto
# tailscale_hostname: ""
# docker_dir: ""
# backup_dir: ""
# tailscale_ip:

# # Vaultwarden
# vaultwarden_signups_allowed: "false"
# vaultwarden_websocket_enabled: "true"

# # AdGuard
# adguard_dns_port: ""
# adguard_web_port: ""

# # Paperless
# paperless_db_name: ""
# paperless_user_name: ""
# paperless_db_password: ""
# paperless_secret_key: ""

# # beszel
# beszel_token: ""
# beszel_key: ""

# # opencloud
# opencloud_admin_password: ""
# opencloud_jwt_secret: ""
# opencloud_transfer_secret: ""
# opencloud_machine_auth_key: ""
